FROM node:20

# Устанавливаем переменную окружения (development или production)
ENV NODE_ENV=development

WORKDIR /usr/app

# Копируем package.json и yarn.lock для кеширования
COPY package.json yarn.lock ./

# Устанавливаем зависимости
RUN yarn install

# Копируем весь проект после установки зависимостей
COPY . . 

RUN mkdir -p /usr/app/logs

# Генерируем Prisma клиент после копирования кода
RUN yarn prisma generate

# Открываем порт 5000
EXPOSE 5000

# Ждём, пока PostgreSQL будет доступен, затем запускаем сервер
CMD ["yarn", "start:dev"]

