FROM node:20

# Устанавливаем переменную окружения (development или production)
ENV NODE_ENV=development

RUN apt-get update && apt-get install -y ffmpeg

WORKDIR /usr/app

RUN npm install -g pnpm

# Копируем package.json для кеширования
COPY package.json pnpm-lock.yaml ./

RUN pnpm install --frozen-lockfile
# Копируем весь проект после установки зависимостей
COPY . . 

# Генерируем Prisma клиент после копирования кода
RUN pnpm prisma generate

# Открываем порт 5000
EXPOSE 5000

# Ждём, пока PostgreSQL будет доступен, затем запускаем сервер
CMD ["sh", "-c", "pnpm prisma db push && pnpm run start:dev"]

