FROM node:20

# Устанавливаем переменную окружения (development или production)
ENV NODE_ENV=development

WORKDIR /usr/app

# Копируем package.json для кеширования
COPY package*.json ./

# Устанавливаем зависимости
RUN npm ci

# Копируем весь проект после установки зависимостей
COPY . . 

# Генерируем Prisma клиент после копирования кода
RUN npx prisma generate

# Открываем порт 5000
EXPOSE 5000

# Ждём, пока PostgreSQL будет доступен, затем запускаем сервер
CMD ["sh", "-c", "npx prisma db push && npm run start:dev"]

