import { useTypedSelector } from "@/hooks/useTypedSelector";
import { Providers } from "@/store/provider";
import type { Metadata } from "next";
import { Suspense } from "react";
import Loading from "./loading";
import AlbumPage from "@/pages/albums/[id]";
import React from "react";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Providers>
      <html lang="ru-RU">
        <head>
        </head>
        <body >
          <React.Fragment>
            <Suspense fallback={<Loading />}>
              {children}
            </Suspense>
        </React.Fragment>
            
        </body>
        
      </html>
    </Providers>
  );
}
