import { useTypedSelector } from "@/hooks/useTypedSelector";
import { Providers } from "@/store/provider";
import type { Metadata } from "next";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Providers>
      <html lang="ru-RU">
        
        <body >
            {children}
        </body>
        
      </html>
    </Providers>
  );
}
