allowBuilds:
  '@ffmpeg-installer/linux-x64': set this to true or false
  '@ffprobe-installer/linux-x64': set this to true or false
  '@nestjs/core': set this to true or false
  '@prisma/client': set this to true or false
  '@prisma/engines': set this to true or false
  '@scarf/scarf': set this to true or false
  nestjs-pino: set this to true or false
  prisma: set this to true or false
  sharp: set this to true or false
ignoredBuiltDependencies:
  - '@nestjs/core'
  - '@prisma/client'
  - '@prisma/engines'
  - '@scarf/scarf'
  - nestjs-pino
  - prisma
onlyBuiltDependencies:
  - '@ffmpeg-installer/linux-x64'
  - '@ffprobe-installer/linux-x64'
  - sharp
